services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:

volumes:
  rabbitmq_data: