version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  create-topic:
    image: 'bitnami/kafka:latest'
    depends_on:
      - kafka
    command: >
      bash -c "sleep 5 && kafka-topics.sh --create --bootstrap-server kafka:9092 --topic pruebas --partitions 1 --replication-factor 1"